app.environment=${RAILWAY_ENVIRONMENT_NAME:local.dev}

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.com.quetoquenana.userservice=DEBUG

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

security.jwt.access-token-seconds=604800

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.security.oauth2.resourceserver.jwt.jws-algorithm=RS256
spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE_ENABLED:false}

spring.jpa.show-sql=true
